// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID        string `json:"id"`
	User      string `json:"user"`
	CreatedAt string `json:"createdAt"`
	Text      string `json:"text"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
