version: '3'
services:
  postgres:
    image: 'postgres:14'
    container_name: postgres_gin
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
      TZ: Asia/Tokyo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - './db-store:/var/lib/postgresql/data'
